pagopa/azuredevops-tf-modules

azuredevops_build_definition_code_review/main.tf, azuredevops_build_definition_code_review/variables.tf
more simple pipeline definition
```
variable "sample-pipeline" {
default = {
repository = {
organization   = "pagopa"
name           = "sample-pipeline"
branch_name    = "master"
pipelines_path = ".devops"
}
pipeline = {
enable_code_review     = true
enable_deploy          = false
enable_azure_pipelines = false
variables = {
}
variables_secret = {
}
code_review_variables = {
}
code_review_variables_secret = {
}
deploy_variables = {
#common env
#use dev prefix
#use uat prefix
#use prod prefix
}
deploy_variables_secret = {
#common env
#use dev prefix
#use uat prefix
#use prod prefix
}
}
}
}
module "sample-pipeline-code_review" {
source = "git::https://github.com:pagopa/azuredevops-tf-modules.git//azuredevops_build_definition_code_review?ref=v0.0.1"
count  = …
```
=> Add code review pipeline module

azuredevops_build_definition_deploy/main.tf, azuredevops_build_definition_deploy/variables.tf
more simple pipeline definition
```
variable "sample-pipeline" {
default = {
repository = {
organization   = "pagopa"
name           = "sample-pipeline"
branch_name    = "master"
pipelines_path = ".devops"
}
pipeline = {
enable_code_review     = false
enable_deploy          = true
enable_azure_pipelines = false
variables = {
}
variables_secret = {
}
code_review_variables = {
}
code_review_variables_secret = {
}
deploy_variables = {
#common env
#use dev prefix
#use uat prefix
#use prod prefix
}
deploy_variables_secret = {
#common env
#use dev prefix
#use uat prefix
#use prod prefix
}
}
}
}
module "sample-pipeline-deploy" {
source = "git::https://github.com:pagopa/azuredevops-tf-modules.git//azuredevops_build_definition_deploy?ref=v0.0.1"
count  = var.sample-pipeline.pipeline.enable_deploy …
```
=> Add deploy pipeline module

azuredevops_build_definition_tls_cert/main.tf, azuredevops_build_definition_tls_cert/variables.tf, azuredevops_serviceendpoint_azurerm_limited/main.tf, azuredevops_serviceendpoint_azurerm_limited/output.tf, azuredevops_serviceendpoint_azurerm_limited/variables.tf
- add TLS cert pipeline
- add service connection with no access
=> Add modules for acme tiny cert pipelines

azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/main.tf, azuredevops_build_definition_tls_cert/variables.tf, azuredevops_serviceendpoint_azurerm_limited/README.md, azuredevops_serviceendpoint_azurerm_limited/main.tf, azuredevops_serviceendpoint_azurerm_limited/output.tf, azuredevops_serviceendpoint_azurerm_limited/variables.tf
use renew token to recreate service principal and its credentials
=> Add renew token

azuredevops_build_definition_certaz/README.md, azuredevops_build_definition_certaz/main.tf, azuredevops_build_definition_certaz/variables.tf, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/main.tf, azuredevops_build_definition_code_review/variables.tf, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/main.tf, azuredevops_build_definition_deploy/variables.tf, azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/main.tf, azuredevops_build_definition_tls_cert/variables.tf, azuredevops_serviceendpoint_azurerm_limited/README.md, azuredevops_serviceendpoint_azurerm_limited/main.tf
=> Add trigger to build definition tls cert

azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/main.tf
=> Unpin terraform azuredevops version

azuredevops_serviceendpoint_azurerm_limited/main.tf
added azurerm provider
allow to remove warning during the running phase
=> chore: Added azurerm provider

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/static_analysis.yml, .pre-commit-config.yaml, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_tls_cert/README.md, azuredevops_serviceendpoint_azurerm_limited/README.md, terraform_run_all.sh
- added terraform_run_all to initialize all the repo
- added static_analysis.yaml action
allow static analysis during pr
=> chore: Added static analysis

.utils/terraform_run_all.sh, README.md, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/main.tf, azuredevops_build_definition_deploy/variables.tf, azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/variables.tf, azuredevops_serviceendpoint_azurerm_limited/README.md
- azuredevops_build_definition_deploy added scheduler
- added scheduler
=> feat: DEVOPS-306-deploy-add-triggers

azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/main.tf, azuredevops_build_definition_deploy/variables.tf
=> feat: Module deploy custom pipeline name

azuredevops_build_definition_certaz/README.md, azuredevops_build_definition_certaz/variables.tf, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/variables.tf, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/main.tf, azuredevops_build_definition_deploy/variables.tf, azuredevops_build_definition_generic/README.md, azuredevops_build_definition_generic/main.tf, azuredevops_build_definition_generic/variables.tf, azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/variables.tf
- upgraded agent pool name to: Azure Pipelines
- added to pull_request_trigger_use_yaml to deploy template
- [] Yes
=> feat: Upgraded agent type and added pull_request_trigger

azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/main.tf, azuredevops_build_definition_code_review/variables.tf
- added parameter pipeline_name_prefix
- Allow to create a different pipeline name
=> fix: CodeReview allow pipeline name prefix

azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/main.tf, azuredevops_build_definition_code_review/variables.tf, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/variables.tf
- fix variables default value
- documentation
Fix pipeline name
=> fix: Pipelines-names for code-review

azuredevops_serviceendpoint_azurerm_limited/README.md, azuredevops_serviceendpoint_azurerm_limited/main.tf, azuredevops_serviceendpoint_azurerm_limited/variables.tf
=> fix: Add default_roleassignment_rg_prefix to azuredevops_serviceendpoint_azurerm_limited

azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/main.tf, azuredevops_build_definition_code_review/variables.tf
=> feat: Add ci_trigger_use_yaml code_review

azuredevops_serviceendpoint_azurerm_limited/versions.tf
=> breaking: Force release

.releaserc.js, azuredevops_serviceendpoint_azurerm_limited/versions.tf
=> breaking: Force-release

azuredevops_serviceendpoint_azurerm_plan/README.md, azuredevops_serviceendpoint_azurerm_plan/main.tf, azuredevops_serviceendpoint_azurerm_plan/output.tf
=> fix: Plan service connection outputs values

azuredevops_build_definition_switcher/README.md, azuredevops_build_definition_switcher/main.tf, azuredevops_build_definition_switcher/variables.tf, azuredevops_build_definition_switcher/versions.tf
Added module to create switcher pipeline
=> feat: Added switcher module

azuredevops_build_definition_resource_switcher/README.md, azuredevops_build_definition_resource_switcher/aks_pipeline.tf, azuredevops_build_definition_resource_switcher/storage_account_pipeline.tf, azuredevops_build_definition_resource_switcher/variables.tf
=> feat: Switcher timeout var

azuredevops_build_definition_resource_switcher/README.md, azuredevops_build_definition_resource_switcher/aks_pipeline.tf, azuredevops_build_definition_resource_switcher/storage_account_pipeline.tf, azuredevops_build_definition_resource_switcher/variables.tf
=> feat: Switcher - added node pool exclusions

azuredevops_build_definition_resource_switcher/aks_pipeline.tf, azuredevops_build_definition_resource_switcher/storage_account_pipeline.tf
=> feat: Fix resource authorization

azuredevops_build_definition_resource_switcher/README.md, azuredevops_build_definition_resource_switcher/aks_pipeline.tf, azuredevops_build_definition_resource_switcher/variables.tf
=> feat: Switcher added force  parameter

azuredevops_build_definition_certaz/README.md, azuredevops_build_definition_certaz/versions.tf, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/versions.tf, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/versions.tf, azuredevops_build_definition_generic/README.md, azuredevops_build_definition_generic/versions.tf, azuredevops_build_definition_resource_switcher/README.md, azuredevops_build_definition_resource_switcher/versions.tf, azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/versions.tf, azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_build_definition_tls_cert_federated/main.tf, azuredevops_build_definition_tls_cert_federated/versions.tf, azuredevops_serviceendpoint_azurerm_limited/README.md, azuredevops_serviceendpoint_azurerm_limited/versions.tf, azuredevops_serviceendpoint_azurerm_plan/README.md, azuredevops_serviceendpoint_azurerm_plan/versions.tf, azuredevops_serviceendpoint_federated/README.md, azuredevops_serviceendpoint_federated/versions.tf
Allow to use azure devops provider version 0.11.0 and 0.12.0
=> feat: Azure devops provider constraint updated <= 0.12.0

azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_build_definition_tls_cert_federated/main.tf
=> fix: Azuredevops_build_definition_tls_cert_federated upgrated module version to avoid azure devops version contraint

azuredevops_serviceendpoint_federated/README.md, azuredevops_serviceendpoint_federated/main.tf, azuredevops_serviceendpoint_federated/variables.tf
=> fix: service endpoint federated now can have a different name

azuredevops_build_definition_code_review/main.tf
Avoid every time to apply this change
=> fix: Ignore code review auto cancel

azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/main.tf, azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_build_definition_tls_cert_federated/main.tf, azuredevops_serviceendpoint_azurerm_limited/README.md, azuredevops_serviceendpoint_azurerm_limited/main.tf, azuredevops_serviceendpoint_azurerm_plan/README.md, azuredevops_serviceendpoint_azurerm_plan/main.tf
Allow to use the last version of modules
=> feat: Upgrated internal modules version

azuredevops_build_definition_certaz/README.md, azuredevops_build_definition_certaz/versions.tf, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/versions.tf, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/versions.tf, azuredevops_build_definition_generic/README.md, azuredevops_build_definition_generic/versions.tf, azuredevops_build_definition_resource_switcher/README.md, azuredevops_build_definition_resource_switcher/versions.tf, azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/versions.tf, azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_build_definition_tls_cert_federated/versions.tf, azuredevops_serviceendpoint_azurerm_limited/README.md, azuredevops_serviceendpoint_azurerm_limited/versions.tf, azuredevops_serviceendpoint_azurerm_plan/README.md, azuredevops_serviceendpoint_azurerm_plan/versions.tf, azuredevops_serviceendpoint_federated/README.md, azuredevops_serviceendpoint_federated/versions.tf
=> feat: Upgrade azurerm provider

azuredevops_build_definition_tls_cert_federated/main.tf
=> feat: Fix dependency version tls cert federated

.github/workflows/static_analysis.yml, .releaserc.js, azuredevops_build_definition_deploy/main.tf, azuredevops_build_definition_generic/main.tf, azuredevops_build_definition_resource_switcher/README.md, azuredevops_build_definition_resource_switcher/aks_pipeline.tf, azuredevops_build_definition_resource_switcher/main.tf, azuredevops_build_definition_resource_switcher/storage_account_pipeline.tf, azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_serviceendpoint_azurerm_limited/versions.tf, azuredevops_serviceendpoint_azurerm_plan/versions.tf, azuredevops_serviceendpoint_federated/versions.tf
Everytime the pipelines during a run, as for a change into pull request auto-cancel, to avoid problem we decided to ignore this field
=> fix: Pipelines with ignore pull request auto-cancel

.pre-commit-config.yaml, .utils/terraform_run_all.sh, README.md
- pre-commit: added new tasks to check files and commits, and updated to version 1.86
- terraform-run-all: now generate terraform locks updated, usefull for pre-commit 
- readme: added how to generate terraform locks
Allow to have more tools for pre-commit and better code checks
=> breaking: Update middleware tools

.github/workflows/pr-title.yml, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/main.tf, azuredevops_build_definition_code_review/variables.tf, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/main.tf, azuredevops_build_definition_deploy/variables.tf, azuredevops_build_definition_generic/README.md, azuredevops_build_definition_generic/main.tf, azuredevops_build_definition_generic/variables.tf
- Added enable flags for ci and pull request triggers
- Changed deploy and ci pipelines default value for use yaml pipelines, to simplify how to use
- minor fix
Allow the use to disable the triggers
=> breaking: (Configuration) Add enable flag triggers for generic, code review, deploy pipelines

azuredevops_build_definition_certaz/README.md, azuredevops_build_definition_certaz/versions.tf, azuredevops_build_definition_code_review/README.md, azuredevops_build_definition_code_review/versions.tf, azuredevops_build_definition_deploy/README.md, azuredevops_build_definition_deploy/versions.tf, azuredevops_build_definition_generic/README.md, azuredevops_build_definition_generic/versions.tf, azuredevops_build_definition_resource_switcher/README.md, azuredevops_build_definition_resource_switcher/versions.tf, azuredevops_build_definition_tls_cert/README.md, azuredevops_build_definition_tls_cert/main.tf, azuredevops_build_definition_tls_cert/versions.tf, azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_build_definition_tls_cert_federated/main.tf, azuredevops_build_definition_tls_cert_federated/versions.tf, azuredevops_serviceendpoint_azurerm_limited/README.md, azuredevops_serviceendpoint_azurerm_limited/main.tf, azuredevops_serviceendpoint_azurerm_limited/versions.tf, azuredevops_serviceendpoint_azurerm_plan/README.md, azuredevops_serviceendpoint_azurerm_plan/main.tf, azuredevops_serviceendpoint_azurerm_plan/versions.tf, azuredevops_serviceendpoint_federated/README.md, azuredevops_serviceendpoint_federated/versions.tf
Updating all versions of the Terraform providers.
Doc here: [version-contraints](https://developer.hashicorp.com/terraform/language/expressions/version-constraints)
=> breaking: All upgrade providers

azuredevops_serviceendpoint_azurecr_federated/README.md, azuredevops_serviceendpoint_azurecr_federated/main.tf, azuredevops_serviceendpoint_azurecr_federated/output.tf, azuredevops_serviceendpoint_azurecr_federated/variables.tf, azuredevops_serviceendpoint_azurecr_federated/versions.tf
Allow to create a azure container registry service connection with federated credentials
=> feat: Created azuredevops_serviceendpoint_azurecr_federated

azuredevops_serviceendpoint_azurerm_plan/variables.tf
Increase the eventhub permissions to plan in IAC pipelines without errors
=> feat(plan): Updated eventhub roles

azuredevops_serviceendpoint_azurerm_plan/variables.tf
=> fix(plan): added "EventGrid Contributor" permission to plan

workflow_tls_cert_service_connection/README.md, workflow_tls_cert_service_connection/versions.tf
=> fix: Force release

azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_build_definition_tls_cert_federated/main.tf, azuredevops_build_definition_tls_cert_federated/variables.tf
=> feat: certdiff pipeline

azuredevops_build_definition_tls_cert_federated/README.md, azuredevops_build_definition_tls_cert_federated/main.tf, azuredevops_build_definition_tls_cert_federated/variables.tf
=> fix: Cert diff pipeline
